package dev.echoellet.dragonfist_legacy.entity.shifu.util

import dev.echoellet.dragonfist_legacy.generated.LangKeys

object ShifuMessageKeys {

    const val SHIFU_KILLED_BY_PLAYER = LangKeys.MESSAGE_SHIFU_KILLED_BY_PLAYER
    const val SHIFU_KILLED_NATURALLY = LangKeys.MESSAGE_SHIFU_DIED_NATURALLY
    const val EXCHANGE_DURING_FIGHT = LangKeys.MESSAGE_SHIFU_EXCHANGE_DURING_FIGHT
    const val BUSY = LangKeys.MESSAGE_SHIFU_BUSY
    const val PATIENCE_BEFORE_LEARNING = LangKeys.MESSAGE_SHIFU_PATIENCE_BEFORE_LEARNING

    object ExchangeSuccess {
        val NORMAL: List<String> = listOf(
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_1,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_2,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_3,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_4,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_5,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_6,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_7,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_8,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_9,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_10,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_11,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_12,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_13,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_14,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_15,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_16,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_17,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_18,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_19,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_20,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_21,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_22,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_23,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_24,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_25,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_26,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_27,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_28,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_29,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_30,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_31,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_32,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_33,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_34,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_35,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_36,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_37,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_38,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_39,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_40,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_41,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_42,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_43,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_44,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_45,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_46,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_47,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_48,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_49,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_50,
        )

        val RAIN: List<String> = listOf(
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_1,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_2,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_3,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_4,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_5,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_6,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_7,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_8,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_9,
            LangKeys.MESSAGE_SHIFU_EXCHANGE_SUCCESS_RAIN_10,
        )
    }

    object Talk {
        val NORMAL: List<String> = listOf(
            LangKeys.MESSAGE_SHIFU_TALK_1,
            LangKeys.MESSAGE_SHIFU_TALK_2,
            LangKeys.MESSAGE_SHIFU_TALK_3,
            LangKeys.MESSAGE_SHIFU_TALK_4,
            LangKeys.MESSAGE_SHIFU_TALK_5,
            LangKeys.MESSAGE_SHIFU_TALK_6,
            LangKeys.MESSAGE_SHIFU_TALK_7,
            LangKeys.MESSAGE_SHIFU_TALK_8,
            LangKeys.MESSAGE_SHIFU_TALK_9,
            LangKeys.MESSAGE_SHIFU_TALK_10,
            LangKeys.MESSAGE_SHIFU_TALK_11,
            LangKeys.MESSAGE_SHIFU_TALK_12,
            LangKeys.MESSAGE_SHIFU_TALK_13,
            LangKeys.MESSAGE_SHIFU_TALK_14,
            LangKeys.MESSAGE_SHIFU_TALK_15,
            LangKeys.MESSAGE_SHIFU_TALK_16,
            LangKeys.MESSAGE_SHIFU_TALK_17,
            LangKeys.MESSAGE_SHIFU_TALK_18,
            LangKeys.MESSAGE_SHIFU_TALK_19,
            LangKeys.MESSAGE_SHIFU_TALK_20,
            LangKeys.MESSAGE_SHIFU_TALK_21,
            LangKeys.MESSAGE_SHIFU_TALK_22,
            LangKeys.MESSAGE_SHIFU_TALK_23,
            LangKeys.MESSAGE_SHIFU_TALK_24,
            LangKeys.MESSAGE_SHIFU_TALK_25,
            LangKeys.MESSAGE_SHIFU_TALK_26,
            LangKeys.MESSAGE_SHIFU_TALK_27,
            LangKeys.MESSAGE_SHIFU_TALK_28,
            LangKeys.MESSAGE_SHIFU_TALK_29,
            LangKeys.MESSAGE_SHIFU_TALK_30,
            LangKeys.MESSAGE_SHIFU_TALK_31,
            LangKeys.MESSAGE_SHIFU_TALK_32,
            LangKeys.MESSAGE_SHIFU_TALK_33,
            LangKeys.MESSAGE_SHIFU_TALK_34,
            LangKeys.MESSAGE_SHIFU_TALK_35,
            LangKeys.MESSAGE_SHIFU_TALK_36,
            LangKeys.MESSAGE_SHIFU_TALK_37,
            LangKeys.MESSAGE_SHIFU_TALK_38,
            LangKeys.MESSAGE_SHIFU_TALK_39,
            LangKeys.MESSAGE_SHIFU_TALK_40,
            LangKeys.MESSAGE_SHIFU_TALK_41,
            LangKeys.MESSAGE_SHIFU_TALK_42,
            LangKeys.MESSAGE_SHIFU_TALK_43,
            LangKeys.MESSAGE_SHIFU_TALK_44,
            LangKeys.MESSAGE_SHIFU_TALK_45,
            LangKeys.MESSAGE_SHIFU_TALK_46,
            LangKeys.MESSAGE_SHIFU_TALK_47,
            LangKeys.MESSAGE_SHIFU_TALK_48,
            LangKeys.MESSAGE_SHIFU_TALK_49,
            LangKeys.MESSAGE_SHIFU_TALK_50,
        )

        val RAIN: List<String> = listOf(
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_1,
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_2,
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_3,
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_4,
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_5,
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_6,
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_7,
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_8,
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_9,
            LangKeys.MESSAGE_SHIFU_TALK_RAIN_10,
        )
    }

    object NotEnoughScrolls {
        val NORMAL: List<String> = listOf(
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_1,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_2,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_3,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_4,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_5,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_6,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_7,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_8,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_9,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_10,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_11,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_12,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_13,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_14,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_15,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_16,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_17,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_18,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_19,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_20,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_21,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_22,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_23,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_24,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_25,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_26,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_27,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_28,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_29,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_30,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_31,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_32,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_33,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_34,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_35,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_36,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_37,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_38,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_39,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_40,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_41,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_42,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_43,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_44,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_45,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_46,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_47,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_48,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_49,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_50,
        )

        val RAIN: List<String> = listOf(
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_1,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_2,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_3,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_4,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_5,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_6,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_7,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_8,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_9,
            LangKeys.MESSAGE_SHIFU_NOT_ENOUGH_SCROLLS_RAIN_10,
        )
    }

    object PlayerTraining {
        object ShifuWins {
            val NORMAL: List<String> = listOf(
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_1,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_2,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_3,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_4,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_5,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_6,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_7,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_8,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_9,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_10,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_11,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_12,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_13,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_14,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_15,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_16,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_17,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_18,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_19,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_20,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_21,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_22,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_23,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_24,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_25,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_26,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_27,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_28,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_29,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_30,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_31,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_32,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_33,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_34,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_35,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_36,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_37,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_38,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_39,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_40,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_41,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_42,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_43,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_44,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_45,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_46,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_47,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_48,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_49,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_50,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_51,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_52,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_53,
            )

            val RAIN: List<String> = listOf(
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_1,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_2,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_3,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_4,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_5,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_6,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_7,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_8,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_9,
                LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_WIN_RAIN_10,
            )
        }

        object PlayerWins {
            val NORMAL: List<String> =
                listOf(
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_1,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_2,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_3,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_4,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_5,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_6,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_7,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_8,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_9,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_10,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_11,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_12,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_13,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_14,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_15,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_16,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_17,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_18,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_19,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_20,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_21,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_22,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_23,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_24,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_25,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_26,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_27,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_28,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_29,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_30,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_31,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_32,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_33,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_34,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_35,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_36,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_37,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_38,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_39,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_40,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_41,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_42,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_43,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_44,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_45,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_46,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_47,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_48,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_49,
                    LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_50,
                )
            val RAIN: List<String> = listOf(
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_1,
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_2,
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_3,
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_4,
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_5,
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_6,
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_7,
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_8,
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_9,
                LangKeys.MESSAGE_SHIFU_TRAINING_PLAYER_WIN_RAIN_10,
            )
        }

        object Start {
            val NORMAL: List<String> =
                listOf(
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_1,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_2,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_3,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_4,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_5,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_6,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_7,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_8,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_9,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_10,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_11,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_12,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_13,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_14,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_15,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_16,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_17,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_18,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_19,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_20,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_21,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_22,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_23,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_24,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_25,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_26,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_27,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_28,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_29,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_30,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_31,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_32,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_33,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_34,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_35,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_36,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_37,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_38,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_39,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_40,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_41,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_42,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_43,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_44,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_45,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_46,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_47,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_48,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_49,
                    LangKeys.MESSAGE_SHIFU_TRAINING_START_50,
                )
            val RAIN: List<String> = listOf(
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_1,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_2,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_3,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_4,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_5,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_6,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_7,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_8,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_9,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_10,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_11,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_12,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_13,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_14,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_15,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_16,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_17,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_18,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_19,
                LangKeys.MESSAGE_SHIFU_TRAINING_START_RAIN_20,
            )
        }
    }

    val RANDOM_RAIN_REACTION: List<String> = listOf(
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_1,
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_2,
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_3,
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_4,
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_5,
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_6,
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_7,
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_8,
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_9,
        LangKeys.MESSAGE_SHIFU_RANDOM_RAIN_REACTION_10,
    )

    const val SHIFU_ACCIDENTALLY_KILLED_PLAYER: String =
        LangKeys.MESSAGE_SHIFU_TRAINING_SHIFU_ACCIDENTALLY_KILLED_PLAYER
    const val PLAYER_LOW_HEALTH: String = LangKeys.ACTIONBAR_SHIFU_PLAYER_LOW_HEALTH
    const val SHIFU_LOW_HEALTH: String = LangKeys.ACTIONBAR_SHIFU_SHIFU_LOW_HEALTH
}
